### ISSUE TITLE
AlertManager接口不能访问

### ISSUE THREAD

**Issue by jinhang** [ZhenyangZhao/am_conf#1]
`AlertManagerUrl = "http://localhost:9093/api/-/reload"` 不能访问？AlertManager开放这个接口了吗？

**Comment by ZhenyangZhao** [comment]
@jinhang AlertManager reload接口 官方调整为 http://alertmanager:9093/-/reload 同prometheus

**Comment by ZhenyangZhao** [comment]
@jinhang 该版本am_conf是为了适配老版本的prometheus&alertmanager，项目建立的时候alertmanager并没有加入reload api。所以提交pull request给alertmanager时候他们采用了api/-/reload后续优化的时候优化成/-/reload，如果使用本项目来完成alertmanager和prometheus重载的话，可以clone本项目修改/api/-/reload 为/-/reload 编译即可
