### ISSUE TITLE
如何用这个接口127.0.0.1:8181/v1/alertmanager/conf 修改 alert的email

### ISSUE THREAD

**Issue by jinhang** [ZhenyangZhao/am_conf#2]
比如修改alertmanager的配置文件中的某个alert的email地址

**Comment by ZhenyangZhao** [comment]
127.0.0.1:8181/v1/alertmanager/conf 
post
rules:{
	"smtp_smarthost": "smtp.sina.com:25",
	"smtp_from": "1111111111111@sina.com",
	"smtp_auth_username": "11111",
	"smtp_auth_password": "11111",
	"group_by": ["alertname",
	"service"],
	"group_wait": "30s",
	"group_interval": "5m",
	"repeat_interval": "2h",
	"receiver_default": "team-X-mails",
	"match_re_routes": [{
		"match_re": "alertname: ^(host_down)$",
		"receiver": "team-X-mails",
		"group_by": ["alertname"],
		"group_wait": "30s"
	},
	{
		"match_re": "alertname: ^(host_memory_usage)$",
		"receiver": "team-Y-mails",
		"group_by": ["alertname"],
		"group_wait": "30s"
	}],
	"receivers": [{
		"name": "team-X-mails",
		"to": "1111111@sina.com"
	},
	{
		"name": "team-Y-mails",
		"to": "1111111@qq.com"
	}]
}
